### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by CoderSaty** [CoderSaty/codersaty#1]
Someone Please add a section in the readme that will list all my competitive programming profiles
1. codechef
2. codeforces
3. geeksforgeeks
4. leetcode
5. hackerrank
6. hackerearth
7. atcoder
8. stopstalk handle.
https://www.stopstalk.com/user/profile/codersaty

**Comment by nikhilshukla07** [comment]
I can do it

**Comment by CoderSaty** [comment]
I have assigned it to you. Please do it

**Comment by b-farhaan** [comment]
Hey @CoderSaty,
I can help you to update this file
Please assign this task to me and I will submit the PR to you

**Comment by CoderSaty** [comment]
Please do it.
